### ISSUE TITLE
About paper's fig

### ISSUE THREAD

**Issue by yanrihong** [dexin-wang/Hierarchical_Diffusion_Policy#1]
Hi!
Thanks for your solid work,
How did you generate this figure in the paper? especially the traj. 
![image](https://github.com/user-attachments/assets/0e1736a6-5845-402b-8b48-b2d7a85b64f6)

**Comment by dexin-wang** [comment]
To generate this image, you need to first collect trajectories and then render the visualization.

We modified the existing `env_runner` code for trajectory collection, but the changes were somewhat messy, so we did not provide a dedicated script for running it.

The rendering process is relatively simple. We have uploaded the collected trajectory data and the rendering code to the project directory: [paper_results](https://github.com/dexin-wang/Hierarchical-Diffusion-Policy/tree/master/paper_results).

You can run `python paper_results/control/draw_control_actions_hdp.py` to generate the image containing both trajectories and prompts.

**Comment by dexin-wang** [comment]
Unfortunately, the trajectory data for the leftmost image was lost due to file overwriting. 
However, you can reproduce all the other images.

**Comment by yanrihong** [comment]
Thank you so much!
